### ISSUE TITLE
PXD-1807 ⁃ create file index mapping and etl

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/tube#18]
we need the file index for the 'download manifest' button,since it's only needed for that button, we dont need to aggregate any fields except for the 'case_id', the traversal path will be different per file type, so the mapping will need to write one block per node, we will need to adjust the mappings and settings to allow:

* pointing to different indices per top level object in mapping. (doc type is deprecated so we shouldn't use it

**Comment by thanh-nguyen-dang** [comment]
```
table_name:
  index: INDEX_NAME
  _props:
    ...
```
also support a configuration of `VERSIONED_INDEX` and default to True,
and before dumping to elasticsaerch,
search for existing es indices that has the INDEX_NAME prefix, and find the largest one, if that's INDEX_NAME_0, the etl will increment the number to create INDEX_NAME_1
